# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2906d9110ec3eaf23aa9e8471eeabeeb602e51617724d28d231e33c1c6a409063360bbf6645d600ecb39352c3b1f8b9f501c8e7bbde790c3d2e54f3112ff270d

test:
  secret_key_base: 4d19eec3259fa9b102f9f46a6e584b7ead35bc992a28399df1f6334e5b35e8406ff23ba48b2a8de4ef0f7a70c2f6240de6f131a8e7ba20bd81f86cff1c3354cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
